version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai_synapse_backend
    command: >
      sh -c "python manage.py migrate &&
             gunicorn ai_synapse.wsgi:application --bind 0.0.0.0:8000"
    # volumes:
    #   # - ./ai_synapse:/app
    #   - static_volume:/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./dev.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ai_synapse_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    env_file:
      - ./dev.env

  db:
    image: postgres:14-alpine
    container_name: ai_synapse_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./dev.env

volumes:
  postgres_data:
  # static_volume: