FROM python:3.10-slim
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Paths are now relative to the root context
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire backend directory into the container's /app directory
COPY ./ai_synapse /app/

EXPOSE 8000
CMD ["gunicorn", "ai_synapse.wsgi:application", "--bind", "0.0.0.0:8000"]