version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-local
    restart: always
    # environment:
    #   POSTGRES_USER: colo
    #   POSTGRES_PASSWORD: colo@123
    #   POSTGRES_DB: colo_db
    env_file:
      - dev.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
