# Generated by Django 4.2.20 on 2025-04-13 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instance_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instance',
            name='image',
            field=models.ForeignKey(help_text='The container image used for this instance.', on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='instance_manager.image'),
        ),
        migrations.AddField(
            model_name='instance',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='instance_manager.server'),
        ),
    ]
